// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCquu40h7Y4IdYgy3xLt5g92pD-u19riOI',
    appId: '1:582808221737:web:6f6bfe32977c4956968438',
    messagingSenderId: '582808221737',
    projectId: 'registration-6000d',
    authDomain: 'registration-6000d.firebaseapp.com',
    storageBucket: 'registration-6000d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp4S3qPA3NCQcyxAOQFx7gzdJ2inhai5o',
    appId: '1:582808221737:android:4c33cf6e6dd1afbd968438',
    messagingSenderId: '582808221737',
    projectId: 'registration-6000d',
    storageBucket: 'registration-6000d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCThgRWNO1HKLM2NnhQ20xhPJmS7CIQRmA',
    appId: '1:582808221737:ios:5ea03a35dd705f2e968438',
    messagingSenderId: '582808221737',
    projectId: 'registration-6000d',
    storageBucket: 'registration-6000d.firebasestorage.app',
    iosBundleId: 'com.example.regform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCThgRWNO1HKLM2NnhQ20xhPJmS7CIQRmA',
    appId: '1:582808221737:ios:5ea03a35dd705f2e968438',
    messagingSenderId: '582808221737',
    projectId: 'registration-6000d',
    storageBucket: 'registration-6000d.firebasestorage.app',
    iosBundleId: 'com.example.regform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCquu40h7Y4IdYgy3xLt5g92pD-u19riOI',
    appId: '1:582808221737:web:104598b47b031473968438',
    messagingSenderId: '582808221737',
    projectId: 'registration-6000d',
    authDomain: 'registration-6000d.firebaseapp.com',
    storageBucket: 'registration-6000d.firebasestorage.app',
  );
}
